### ISSUE TITLE
Consistent documentation of S3 methods

### ISSUE THREAD

**Issue by marcusmunch** [ssi-dk/SCDB#69]
All S3 methods should be adequately linked with `@name` and `@rdname`.

From the current state of the [Diseasy coding standard](http://github.com/ssi-dk/diseasy/wiki) and related sources, there is no one way of going about this. I have opened ssi-dk/diseasy#76 to address this.

If a guideline for S3 methods is decided on, all S3 methods exported by SCDB should be reviewed to determine whether or not they are adequately linked:

* [ ] db_timestamp
* [ ] get_schema
* [ ] get_tables
* [ ] mysummary
* [ ] schema_exists
* [ ] table_exists

**Comment by marcusmunch** [comment]
@RasmusSkytte Since this issue was opened, the [Roxygen documentation on S3 method documentation](https://roxygen2.r-lib.org/articles/rd-other.html#s3) has been changed. It now reads (my emphasis):

> It is your choice whether or not to document S3 methods. Generally, it’s not necessary to document **straightforward methods for common generics** like [print()](https://rdrr.io/r/base/print.html). (You should, however, always `@export` S3 methods).

**Comment by RasmusSkytte** [comment]
It seems we may have to take a non-consistent approach and document on a per function basis.

For cases such as `get_schema()`, `get_catalog()`, and `id()` it seems preferable to have all the possible dispatches listed.
In each case, the documentation outlines how these functions varies between dispatches, so I would continue this trend and ensure all dispatches are listed.

For `getTableSignature()` I would just keep it generic.

For `digest_to_checksum()` I am torn. On one hand, I would like to mention that most backends use md5 and SQL Server uses SHA_256. In that case, I would then have the different options listed as for `get_schema()`, `get_catalog()` and `id()`.

**Comment by marcusmunch** [comment]
I see nothing wrong in handling this on a per-function basis, and as I understood the updated Roxygen documentation, is kinda implied.

As I read your comment, your argument in favor of documenting all possible dispatches is to showcase the variety of available dispatches? For the major part[^mssql_temp], I am inclined to disagree; as long as inputs (how to call the function, including all named parameters) and outputs (return values) are identical, I do not see why the inner workings of functions should not just go into "Details" instead.

For `digest_to_checksum()`, similarly[^checksum_longtext]: As long as tables are kept within (cryptographically 🙂) similar backends, the specific algorithm used is more of a **nice** to know than a **need** to know IMO.

[^mssql_temp]: A good example of where I would actually document a dispatch is in [``get_catalog.Microsoft SQL Server`](https://github.com/ssi-dk/SCDB/blob/dcfb406f44bc3f78bc9f2b9906afd654363e1f9e/R/get_catalog.R#L32), which has an additional argument `temporary = FALSE`.

[^checksum_longtext]: Specifically, I would document the difference in algorithms in one of two ways:
  One way is to specify it in "Details", e.g. "For most backends, an MD5 algorithm is used. Currently, the only exception to this is for Microsoft SQL Server, which uses SHA-256". Another way to do it would be to export an object `.hashing_algorithms` containing information on algorithms per backend.
  Either way it should probably be noted somewhere that hashing is not consistent across backends and updating a (hashed) table naïvely copied from one backend to another could result in full-loads.

**Comment by RasmusSkytte** [comment]
PR #115 goes through the documentation of the package and aligns the style to what is discussed here.

Initially, my view was that showing all possible dispatches was the easiest way to 1) be consistent and 2) be transparent, but it does not seem that this is a widely adopted solution and from the discussions here, that we internally believe this to be a good idea.
What convinced my to change my mind on this issue was a simple thought experiment: What if instead of using S3 dispatch, we had used a simple `if, elseif, .. else` structure? In this case we would just do as above and describe in the documentation the differences between the output based on the input.

In #115, we now only list explicitly the S3 methods which have a different function signature from the rest and use itemised lists in the Roxygen docs to document the differences between the dispatches.
In this way, we are more transparent than had we used a `if, elseif, .. else` but not "spamming" the documentation overly so with repeated function signatures.
